on: ["push", "pull_request"]

name: Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC: ${{secrets.mainnet_rpc}}
      KOVAN_RPC: ${{secrets.kovan_rpc}}
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Python cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install python dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -r test_brownie/requirements.txt

      - name: Install yarn dependencies
        run: yarn

      - name: Compile contracts
        run: yarn compile

      - name: Check size
        run: yarn size

      - name: Run tests
        run: yarn test
