name: Update docs
on:
  push:
    branches:
      - "main"

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> docs
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: main
          target_branch: docs
          github_token: ${{ github.token }}
