on: ["push"]

name: Notification

jobs:
  notify:
    steps:
      - name: Notify chat 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_API_KEY }}
          token: ${{ secrets.TELEGRAM_CHAT_1 }}
          message: |
            Commit ${{ commit.sha }} to ${{ repo }} ${{repo.namespace}}
            ${{github.event.name}} ${{github.event.path}} ${{github.workspace}} ${{github.action}}
