on: ["push"]

name: Notification

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify chat 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_1 }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ⚡️ ${{ github.actor }} pushed `${{ github.event.head_commit.message }}` (https://github.com/${{ github.repository }}/commit/${{ github.sha }}) to branch ${{ github.ref }}
