on: ["push"]

name: Stats

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Install github stats
        run: |
          cd /tmp
          sudo apt-get update
          sudo apt-get install bsdmainutils
          git clone https://github.com/arzzen/git-quick-stats.git
          cd git-quick-stats
          sudo make install
          cd /tmp

      - uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Collect stats
        id: stats
        run: |
          export _GIT_SINCE=$(date -dmonday +%Y-%m-%d)
          export _GIT_LOG_OPTIONS="--no-merges --all"
          STATS=$(git-quick-stats -T)
          echo "STATS<<EOF" >> $GITHUB_ENV
          echo "$STATS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify chat 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_1 }}
          token: ${{ secrets.TELEGRAM_API_KEY }}
          message: |
            📊 ${{env.STATS}}
